plugins {
    id 'idea'
    id 'java-library'
    id 'maven-publish'
    id 'eclipse'
    alias(libs.plugins.neo.moddev)
}

// MagitechのMOD ID
String modId = 'magitech'

base {
    archivesName = modId // jarのファイル名
    group = 'net.stln.magitech'
    version = libs.versions.magitech.get() // Magitechのバージョン
}

// This block of code expands all declared replace properties in the specified resource targets.
// A missing property will result in an error. Properties are expanded using ${} Groovy notation.
TaskProvider<ProcessResources> generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            // minecraft_version      : minecraft_version,
            // minecraft_version_range: minecraft_version_range,
            // neo_version            : neo_version,
            // neo_version_range      : neo_version_range,
            // loader_version_range   : loader_version_range,
            mod_id     : modId,
            // mod_name               : mod_name,
            // mod_license            : mod_license,
            mod_version: rootProject.version,
            // mod_authors            : mod_authors,
            // mod_description        : mod_description
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}

// mainモジュールの定義
SourceSet mainModule = sourceSets.named("main") {
    resources {
        // データ生成の出力先もリソースに含める
        srcDirs("src/generated/resources", generateModMetadata.get().outputs.files)
        // ただし.cache配下のファイルは含めない
        exclude("**/.cache/**")
    }
}.get()
// integrationモジュールの定義
SourceSet integrationModule = sourceSets.register("integration") {
    // ここでmainモジュールのコードや依存関係にアクセスできるようにしている
    compileClasspath += mainModule.output + mainModule.compileClasspath
    runtimeClasspath += mainModule.output + mainModule.runtimeClasspath
}.get()

repositories {
    mavenLocal()
    maven {
        url = "https://www.cursemaven.com"
        content {
            includeGroup("curse.maven")
        }
    }
    maven {
        url = "https://api.modrinth.com/maven"
        content {
            includeGroup("maven.modrinth")
        }
    }

    maven { url = "https://maven.architectury.dev/" } // Arch
    maven { url = "https://maven.blamejared.com/" } // Patchouli, Ars, JEI
    maven { url = "https://maven.createmod.net" } // Create, Flywheel
    maven { url = "https://maven.ftb.dev/" } // FTB
    maven { url = "https://maven.minecraftforge.net" } // TerraBlender
    maven { url = "https://maven.rover656.dev/releases" } // EIO
    maven { url = "https://maven.saps.dev/releases" } // AA
    maven { url = "https://maven.shadowsoffire.dev/releases" } // HNN
    maven { url = "https://maven.su5ed.dev/releases" } // FFAPI
    maven { url = "https://maven.tamaized.com/releases" } // Twilight
    maven { url = "https://maven.teamresourceful.com/repository/maven-public/" } // Athena
    maven { url = "https://maven.terraformersmc.com/" } // EMI
    maven { url = "https://maven.theillusivec4.top/" } // Curios
    maven { url = "https://maven.wispforest.io/releases" } // Accessories
    maven { url = "https://modmaven.dev/" } // AU, Mekanism, MI, PnC, Oritech
    maven { url = "https://mvn.devos.one/snapshots" } // Registrate
    maven { url = "https://registry.somethingcatchy.net/repository/maven-releases/" } // Moonlight

    maven {
        url = "https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/"
        content { includeGroup("software.bernie.geckolib") } // GeckoLib
    }
    maven {
        url = "https://dl.cloudsmith.io/public/klikli-dev/mods/maven/"
        content { includeGroup("com.klikli_dev") } // Theurgy
    }
}

neoForge {
    // NeoForgeのバージョン
    version = libs.versions.neo.version.get()

    // Parchment MCのバージョン
    parchment {
        minecraftVersion = '1.21.1'
        mappingsVersion = '2024.11.17'
    }

    // This line is optional. Access Transformers are automatically detected
    // accessTransformers = project.files('src/main/resources/META-INF/accesstransformer.cfg')

    // Default run configurations.
    // These can be tweaked, removed, or duplicated as needed.
    runs {
        // runClient ではJEIやJadeなどの最低限のmodのみを含める
        client {
            client()

            // Comma-separated list of namespaces to load gametests from. Empty = all namespaces.
            systemProperty('neoforge.enabledGameTestNamespaces', modId)
            devLogin = true
        }

        // ここで runIntegration という起動構成が追加される
        // runIntegration で起動すると連携modが読み込まれた状態でプレイできる
        integration {
            client()
            // 参照するモジュールをintegrationに変更
            sourceSet = integrationModule

            systemProperty('neoforge.enabledGameTestNamespaces', modId)
            devLogin = true
        }

        server {
            server()
            programArguments.add('--nogui')
            systemProperty('neoforge.enabledGameTestNamespaces', modId)
        }

        // This run config launches GameTestServer and runs all registered gametests, then exits.
        // By default, the server will crash when no gametests are provided.
        // The gametest system is also enabled by default for other run configs under the /test command.
        gameTestServer {
            type = "gameTestServer"
            systemProperty('neoforge.enabledGameTestNamespaces', modId)
        }

        data {
            data()

            // example of overriding the workingDirectory set in configureEach above, uncomment if you want to use it
            // gameDirectory = project.file('run-data')

            // Specify the modid for data generation, where to output the resulting resource, and where to look for existing resources.
            programArguments.addAll(
                    '--mod', modId,
                    '--all',
                    '--output', file('src/generated/resources/').getAbsolutePath(),
                    '--existing', file('src/main/resources/').getAbsolutePath()
            )
        }

        // applies to all the run configs above
        configureEach {
            // Recommended logging data for a userdev environment
            // The markers can be added/remove as needed separated by commas.
            // "SCAN": For mods scan.
            // "REGISTRIES": For firing of registry events.
            // "REGISTRYDUMP": For getting the contents of all registries.
            systemProperty('forge.logging.markers', 'REGISTRIES')

            // Recommended logging level for the console
            // You can set various levels here.
            // Please read: https://stackoverflow.com/questions/2031163/when-to-use-the-different-log-levels
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        // define mod <-> source bindings
        // these are used to tell the game which sources are for which mod
        // mostly optional in a single mod project
        // but multi mod projects should define one per mod
        create(modId) {
            sourceSet(mainModule)
            sourceSet(integrationModule)
        }
    }

    ideSyncTask(generateModMetadata)
}

// Sets up a dependency configuration called 'localRuntime'.
// This configuration should be used instead of 'runtimeOnly' to declare
// a dependency that will be present for runtime testing but that is
// "optional", meaning it will not be pulled by dependents of this mod.
configurations {
    runtimeClasspath.extendsFrom(localRuntime)
    compileClasspath.extendsFrom(integrationCompileClasspath)
}

dependencies {
    implementation(libs.bundles.common.impl)
    implementation(libs.modonomicon) { transitive = false }
    compileOnly(libs.bundles.common.compile)
    localRuntime(libs.bundles.common.runtime)

    runtimeOnly "curse.maven:appleskin-248787:${appleskin_id}"
    runtimeOnly "curse.maven:auth-me-356643:6177873"
    runtimeOnly "maven.modrinth:xaeros-world-map:arbQPyvf"
    runtimeOnly "maven.modrinth:open-parties-and-claims:c2oTZgsF"
    runtimeOnly "maven.modrinth:xaeros-minimap:CatMvRfN"
    runtimeOnly "curse.maven:advancements-reloaded-1113876:5835520"
    runtimeOnly "maven.modrinth:cloth-config:izKINKFg"

    runtimeOnly "maven.modrinth:emi:ouSj7NfF"
    implementation "maven.modrinth:LNytGWDc:UjX6dr61"
    runtimeOnly "maven.modrinth:oWaK0Q19:44pLdPGg"
    implementation "maven.modrinth:T9PomCSv:U678xqle"

    runtimeOnly "maven.modrinth:mekanism:5KzzycBT"
    runtimeOnly "maven.modrinth:malum:BIbVs1fo"
    runtimeOnly "maven.modrinth:ars-nouveau:jQHRV6Y0"
    runtimeOnly "maven.modrinth:irons-spells-n-spellbooks:Cu7ovsnN"
    runtimeOnly "maven.modrinth:supplementaries:i5gsy1xF"
    implementation "maven.modrinth:twkfQtEc:uPJlV3eS"
    runtimeOnly "maven.modrinth:OFVYKsAk:a6gl7srE"
    runtimeOnly "maven.modrinth:artifacts:rGPw090r"
    runtimeOnly "maven.modrinth:Adega8YN:PQzuABde"
    runtimeOnly "maven.modrinth:L3Jv0QZI:czVeSmZo"
    runtimeOnly "maven.modrinth:kjZCvAn6:bcszfrVc"
    runtimeOnly "maven.modrinth:iGEl6Crx:EAjbdreT"
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}

// このプロジェクトが使用するJavaのバージョン
int jdkVersion = 21

java {
    // source.jarの生成を有効か
    withSourcesJar()
    // 使用するJavaのバージョンを指定
    toolchain {
        languageVersion = JavaLanguageVersion.of(jdkVersion)
    }
    JavaVersion javaVersion = JavaVersion.toVersion(jdkVersion)
    sourceCompatibility = javaVersion
    targetCompatibility = javaVersion
}

tasks {
    compileJava {
        options.encoding = 'UTF-8'
    }

    jar {
        // jarを出力する時にintegrationモジュールも含めるようにする
        from(integrationModule.output)
    }
}
