plugins {
    id 'idea'
    id 'java-library'
    id 'maven-publish'
    id 'eclipse'
    alias(libs.plugins.neo.moddev)
}

String modId = 'magitech'

base {
    archivesName = modId
    group = 'net.stln.magitech'
    version = libs.versions.magitech.get()
}

// This block of code expands all declared replace properties in the specified resource targets.
// A missing property will result in an error. Properties are expanded using ${} Groovy notation.
TaskProvider<ProcessResources> generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            // minecraft_version      : minecraft_version,
            // minecraft_version_range: minecraft_version_range,
            // neo_version            : neo_version,
            // neo_version_range      : neo_version_range,
            // loader_version_range   : loader_version_range,
            mod_id     : modId,
            // mod_name               : mod_name,
            // mod_license            : mod_license,
            mod_version: rootProject.version,
            // mod_authors            : mod_authors,
            // mod_description        : mod_description
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}

SourceSet mainModule = sourceSets.named("main") {
    resources {
        srcDirs("src/generated/resources", generateModMetadata.get().outputs.files)
        exclude("**/.cache/**")
    }
}.get()
SourceSet integrationModule = sourceSets.register("integration") {
    compileClasspath += mainModule.output + mainModule.compileClasspath
    runtimeClasspath += mainModule.output + mainModule.runtimeClasspath
}.get()

repositories {
    mavenLocal()
    maven {
        url "https://www.cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
    }
    maven {
        name = 'GeckoLib'
        url 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/'
        content {
            includeGroup("software.bernie.geckolib")
        }
    }
    maven {
        url "https://maven.su5ed.dev/releases"
    }
    maven {
        // location of the maven that hosts JEI files since January 2023
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
    }
    maven {
        url "https://dl.cloudsmith.io/public/klikli-dev/mods/maven/"
        content {
            includeGroup "com.klikli_dev"
        }
    }
    maven {
        // location of a maven mirror for JEI files, as a fallback
        name = "ModMaven"
        url = "https://modmaven.dev"
    }
    maven { url = 'https://maven.minecraftforge.net/' }
    maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
}

neoForge {
    version = libs.versions.neo.version.get()

    parchment {
        minecraftVersion = '1.21.1'
        mappingsVersion = '2024.11.17'
    }

    // This line is optional. Access Transformers are automatically detected
    // accessTransformers = project.files('src/main/resources/META-INF/accesstransformer.cfg')

    // Default run configurations.
    // These can be tweaked, removed, or duplicated as needed.
    runs {
        client {
            client()

            // Comma-separated list of namespaces to load gametests from. Empty = all namespaces.
            systemProperty('neoforge.enabledGameTestNamespaces', modId)
            devLogin = true
        }

        integration {
            client()
            sourceSet = integrationModule

            systemProperty('neoforge.enabledGameTestNamespaces', modId)
            devLogin = true
        }

        server {
            server()
            programArguments.add('--nogui')
            systemProperty('neoforge.enabledGameTestNamespaces', modId)
        }

        // This run config launches GameTestServer and runs all registered gametests, then exits.
        // By default, the server will crash when no gametests are provided.
        // The gametest system is also enabled by default for other run configs under the /test command.
        gameTestServer {
            type = "gameTestServer"
            systemProperty('neoforge.enabledGameTestNamespaces', modId)
        }

        data {
            data()

            // example of overriding the workingDirectory set in configureEach above, uncomment if you want to use it
            // gameDirectory = project.file('run-data')

            // Specify the modid for data generation, where to output the resulting resource, and where to look for existing resources.
            programArguments.addAll(
                    '--mod', modId,
                    '--all',
                    '--output', file('src/generated/resources/').getAbsolutePath(),
                    '--existing', file('src/main/resources/').getAbsolutePath()
            )
        }

        // applies to all the run configs above
        configureEach {
            // Recommended logging data for a userdev environment
            // The markers can be added/remove as needed separated by commas.
            // "SCAN": For mods scan.
            // "REGISTRIES": For firing of registry events.
            // "REGISTRYDUMP": For getting the contents of all registries.
            systemProperty('forge.logging.markers', 'REGISTRIES')

            // Recommended logging level for the console
            // You can set various levels here.
            // Please read: https://stackoverflow.com/questions/2031163/when-to-use-the-different-log-levels
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        // define mod <-> source bindings
        // these are used to tell the game which sources are for which mod
        // mostly optional in a single mod project
        // but multi mod projects should define one per mod
        create(modId) {
            sourceSet(mainModule)
            sourceSet(integrationModule)
        }
    }

    ideSyncTask(generateModMetadata)
}

// Sets up a dependency configuration called 'localRuntime'.
// This configuration should be used instead of 'runtimeOnly' to declare
// a dependency that will be present for runtime testing but that is
// "optional", meaning it will not be pulled by dependents of this mod.
configurations {
    runtimeClasspath.extendsFrom(localRuntime)
    compileClasspath.extendsFrom(integrationCompileClasspath)
}

dependencies {
    compileOnly "mezz.jei:jei-${minecraft_version}-neoforge-api:${jei_version}"
    runtimeOnly "mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}"
    implementation "maven.modrinth:jade:${jade_id}"
    implementation "curse.maven:curios-309927:${curiosapi_id}"
    implementation "curse.maven:playeranimator-658587:${playeranimator_id}"
    implementation ("com.klikli_dev:modonomicon-${minecraft_version}-neoforge:${modonomicon_version}"){transitive=false}
    implementation "com.github.glitchfiend:TerraBlender-neoforge:1.21.1-4.1.0.8"
    implementation "software.bernie.geckolib:geckolib-neoforge-${minecraft_version}:${geckolib_id}"
    compileOnlyApi "team.lodestar.lodestone:lodestone:${minecraft_version}-${lodestone_version}"
    runtimeOnly "team.lodestar.lodestone:lodestone:${minecraft_version}-${lodestone_version}"

//    implementation "org.spongepowered:mixin:0.7-SNAPSHOT"

    runtimeOnly "curse.maven:appleskin-248787:${appleskin_id}"
    runtimeOnly "curse.maven:auth-me-356643:6177873"
    runtimeOnly "maven.modrinth:xaeros-world-map:arbQPyvf"
    runtimeOnly "maven.modrinth:open-parties-and-claims:c2oTZgsF"
    runtimeOnly "maven.modrinth:xaeros-minimap:CatMvRfN"
    runtimeOnly "curse.maven:advancements-reloaded-1113876:5835520"
    runtimeOnly "maven.modrinth:cloth-config:izKINKFg"

//    runtimeOnly clientModulesOnly("maven.modrinth:emixx:sdRUQHCL")
//    runtimeOnly "maven.modrinth:emiffect:S6Q6duUj"
//    runtimeOnly "maven.modrinth:emi-loot:QXkODMCT"
//    runtimeOnly "maven.modrinth:emi-enchanting:ZyJ6TKvh"
//    runtimeOnly "maven.modrinth:emi-ores:1jY6MIrK"

    runtimeOnly "maven.modrinth:emi:ouSj7NfF"
    implementation "maven.modrinth:LNytGWDc:UjX6dr61"
    runtimeOnly "maven.modrinth:oWaK0Q19:44pLdPGg"
    implementation "maven.modrinth:T9PomCSv:U678xqle"
//    runtimeOnly "maven.modrinth:sodium:Pb3OXVqC"
//    runtimeOnly "maven.modrinth:iris:t3ruzodq"

    runtimeOnly "maven.modrinth:mekanism:5KzzycBT"
    runtimeOnly "maven.modrinth:malum:BIbVs1fo"
    runtimeOnly "maven.modrinth:ars-nouveau:jQHRV6Y0"
    runtimeOnly "maven.modrinth:irons-spells-n-spellbooks:Cu7ovsnN"
    runtimeOnly "maven.modrinth:supplementaries:i5gsy1xF"
    implementation "maven.modrinth:twkfQtEc:uPJlV3eS"
    runtimeOnly "maven.modrinth:OFVYKsAk:a6gl7srE"
    runtimeOnly "maven.modrinth:artifacts:rGPw090r"
    runtimeOnly "maven.modrinth:Adega8YN:PQzuABde"
    runtimeOnly "maven.modrinth:L3Jv0QZI:czVeSmZo"
    runtimeOnly "maven.modrinth:kjZCvAn6:bcszfrVc"
    runtimeOnly "maven.modrinth:iGEl6Crx:EAjbdreT"

//    runtimeOnly("curse.maven:selene-499980:6818413")
//    runtimeOnly("curse.maven:cloth-config-348521:5729127")
//    runtimeOnly("curse.maven:create-328085:6641610")

    // Example optional mod dependency with JEI
    // The JEI API is declared for compile time use, while the full JEI artifact is used at runtime
    // compileOnly "mezz.jei:jei-${mc_version}-common-api:${jei_version}"
    // compileOnly "mezz.jei:jei-${mc_version}-neoforge-api:${jei_version}"
    // We add the full version to localRuntime, not runtimeOnly, so that we do not publish a dependency on it
    // localRuntime "mezz.jei:jei-${mc_version}-neoforge:${jei_version}"

    // Example mod dependency using a mod jar from ./libs with a flat dir repository
    // This maps to ./libs/coolmod-${mc_version}-${coolmod_version}.jar
    // The group id is ignored when searching -- in this case, it is "blank"
    // implementation "blank:coolmod-${mc_version}:${coolmod_version}"

    // Example mod dependency using a file as dependency
    // implementation files("libs/coolmod-${mc_version}-${coolmod_version}.jar")

    // Example project dependency using a sister or child project:
    // implementation project(":myproject")

    // For more info:
    // http://www.gradle.org/docs/current/userguide/artifact_dependencies_tutorial.html
    // http://www.gradle.org/docs/current/userguide/dependency_management.html
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}

int jdkVersion = 25

java {
    withSourcesJar()
    toolchain {
        languageVersion = JavaLanguageVersion.of(jdkVersion)
    }
    JavaVersion javaVersion = JavaVersion.toVersion(jdkVersion)
    sourceCompatibility = javaVersion
    targetCompatibility = javaVersion
}

tasks {
    compileJava {
        options.encoding = 'UTF-8'
    }

    jar {
        from(integrationModule.output)
    }
}
